import { CASINGS, CHEMS, SOURCE, SOURCE_LINKS } from '../data.js';

export function renderReference(root){
  const base=`https://github.com/${SOURCE.repo}/blob/${SOURCE.commit}/`;
  root.innerHTML=`
    <div class="page-head"><div><span class="eyebrow">справочник</span><h1>Что именно считает приложение</h1><p>Короткая документация, чтобы цифры не превращались в магию.</p></div><span class="pill">repo ${SOURCE.shortCommit}</span></div>
    <section class="panel docs"><h2>Взрыв — не линейный круг</h2><p>OT сначала считает <code>Power</code> и <code>Falloff</code>. Затем сервер получает <code>maxIntensity = Power/5</code>, <code>slope = Falloff/5</code> и отдельный <code>totalIntensity</code>. Дальше ExplosionSystem распределяет этот бюджет по tile flood-fill. Поэтому <b>Power/Falloff — параметр формулы, а не гарантированный радиус поражения</b>.</p><p>В пустой сетке прямой сосед появляется через 2 итерации, диагональный — через 3. Приложение воспроизводит именно эту open-grid часть. Стены и airtight blockers в браузере пока не моделируются.</p></section>
    <section class="panel docs"><h2>Урон ксено</h2><p>RMC-взрыв даёт по 5 Blunt + 5 Heat за единицу tile intensity. Базовый Xeno ExplosionResistance умножает урон на 2, после чего ExplosionArmor делит коэффициент на <code>1.1^(EA/5)</code>. Затем взрыв применяется с <code>ignoreResistances: true</code>, поэтому обычный XenoArmor второй раз поверх blast не применяется.</p><p>Шрапнель — другое дело: <code>CMProjectileShrapnel</code> наносит 25 Piercing с AP20 и проходит через обычную систему брони. Направления осколков случайные, если корпус не переключён в directional режим.</p></section>
    <section class="panel docs"><h2>Две гранаты</h2><p>Если два взрыва одного типа попадают в очередь практически одновременно, находятся не дальше 1 тайла и проходят условия attribution, ExplosionSystem может объединить их: складывается <code>TotalIntensity</code>, но параметры первого queued explosion остаются. Поэтому «одновременно» и «два последовательных попадания» — не одно и то же. В боевом симуляторе есть оба режима.</p></section>
    <section class="panel docs"><h2>Огонь</h2><p>После химических clamp'ов сервер приводит Fire Radius / Intensity / Duration к <b>целым числам</b>. При <code>Intensity &gt; 30</code> и <code>AllowStarShape</code> огонь создаётся линиями/звездой. Ракетная боеголовка отключает star-shape.</p></section>
    <section class="panel"><div class="panel-head"><div><span class="eyebrow">Корпуса</span><h2>Лимиты</h2></div></div><div class="table-wrap"><table><thead><tr><th>Корпус</th><th>Объём</th><th>P cap</th><th>Base F</th><th>Min F</th><th>Shards</th><th>Fire max I/R/D</th></tr></thead><tbody>${Object.values(CASINGS).map(c=>`<tr><td>${c.name}</td><td>${c.volume}</td><td>${c.powerCap}</td><td>${c.baseFalloff}</td><td>${c.minFalloff}</td><td>${c.shardCap}</td><td>${c.fire.i[1]} / ${c.fire.r[1]} / ${c.fire.d[1]}</td></tr>`).join('')}</tbody></table></div></section>
    <section class="panel"><div class="panel-head"><div><span class="eyebrow">Источники</span><h2>Текущий public master</h2></div></div><div class="source-list">${SOURCE_LINKS.map(([name,path])=>`<a href="${base+path}" target="_blank" rel="noreferrer"><b>${name}</b><span>${path}</span></a>`).join('')}</div></section>
    <section class="panel"><div class="panel-head"><div><span class="eyebrow">Скрытые реагенты</span><h2>Почему их нет в конструкторе</h2></div></div><div class="need-list">${Object.entries(CHEMS).filter(([,c])=>c.available===false).map(([,c])=>`<div class="need-row"><span>${c.name}<small>${c.unavailableReason}</small></span><b>скрыт</b></div>`).join('')}</div></section>`;
}
